GET http://localhost:3300/pokemon/10
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwc2V1ZG8iOiJwc2V1ZG9UZXN0IiwicGFzc3dvcmQiOiIkMmIkMTAkMi9sZ0ZXTXd3TUVMcTFYNWMycldST29zRnV6akQ1eUJtLnJyNUl6Y1NvWU9tRnNtNmRQUm0iLCJpYXQiOjE3MDkxNDY0MjN9.0kFfBVeBtoNS4cpRUlppFirooHnT26MhjuzkaW7zaAE
Content-Type: application/json

### Error

GET http://localhost:3300/blabla
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwc2V1ZG8iOiJwc2V1ZG9UZXN0IiwicGFzc3dvcmQiOiIkMmIkMTAkMi9sZ0ZXTXd3TUVMcTFYNWMycldST29zRnV6akQ1eUJtLnJyNUl6Y1NvWU9tRnNtNmRQUm0iLCJpYXQiOjE3MDkxNDY0MjN9.0kFfBVeBtoNS4cpRUlppFirooHnT26MhjuzkaW7zaAE
Content-Type: application/json